server:
  port: 9094
  shutdown: graceful
  netty:
    connection-timeout: 3s
    idle-timeout: 20s

spring:
  application:
    name: aggregate-service
  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  client:
    service-url:
      defaultZone: ${external.discovery-service-url}
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true

external:
  discovery-service-url: http://localhost:8761/eureka/
  course-service-url: "http://course-service"
  feedback-service-url: "http://feedback-service"
  course-item-path: "/v1/courses"
  course-feedbacks-path: "/v1/feedbacks/course"
  course-ratings-path: "/v1/feedbacks/ratings"
  default-timeout: 2s
  retry-backoff: 100ms
  retry-count: 5
  retry-jitter: 0.75
  zipkin-endpoint: http://localhost:9411/api/v2/spans
  loki-url: http://localhost:3100/loki/api/v1/push

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: ${external.zipkin-endpoint}
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
#    enable:
#      jvm: true
#      http:
#        server: true
#      netty: true # reactive apps
#      reactor: true # reactive apps
#      executor: true # only if using ThreadPoolTaskExecutor
      # hikaricp: true
      # tomcat: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: time_based
        sliding-window-size: 30 # sec
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 60 # %
        wait-duration-in-open-state:
          seconds: 10
        slow-call-duration-threshold:
          seconds: 4s
        # количество вызовов, по которым принимается решение открыть / закрыть circuitBreaker
        # так как мы используем тип окна TIME_BASED, это количество вызовов должно произойти за
        # указанное в параметре sliding-window-size время.
        minimum-number-of-calls: 15
    instances:
      # Определяем CircuitBreaker, который будет использоваться в CourseClient
      courseBackend:
        base-config: default
      # Определяем CircuitBreaker, который будет использоваться в FeedbacksClient
      feedbackBackend:
        base-config: default

  retry:
    configs:
      default:
        max-attempts: ${external.retry-count} # Максимальное количество попыток выполнения операции
        wait-duration: # Продолжительность ожидания между попытками.
          seconds: ${external.retry-backoff}
        enable-exponential-backoff: true # Включаем экспоненциальное увеличения времени ожидания между попытками.
        exponential-backoff-multiplier: 2 # Множитель экспоненциального увеличения времени ожидания.
        enable-randomized-wait: true #  Включаем случайную задержку между попытками.
        randomized-wait-factor: ${external.retry-jitter} # Это означает, что фактическое время ожидания будет варьироваться на retry-jitter% от исходного значения.
        retry-exceptions: # Список исключений, при возникновении которых будут выполнены повторные попытки.
          - at.aggregate_service.exception.CourseAggregateException
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
      courseBackend:
        base-config: default
      feedbackBackend:
        base-config: default

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

api:
  get-aggregate:
    summary: Get detailed information about a course by its identifier
    description: |
      Provides information about a course, user feedback on it, and its rating.
      If it is not possible to retrieve the rating or user feedback information, 
      a partial response is returned indicating an error while loading the data.
      The list of feedback entries is sorted and paginated according to the request parameters.
      Sorting options:
      - date_asc — by creation date, from oldest to newest
      - date_desc — by creation date, from newest to oldest
  get-aggregate-list:
    summary: Get a list of courses and their ratings from a specific category
    description: |
      Provides a list of courses containing additional information for each course:
      - rating
      - average score
      The list is sorted according to the request parameters.
      Sorting options:
      - az / za — by name alphabetically or in reverse order
      - date_asc / date_desc — by creation date
      - price_asc / price_desc — by price
      - rate_asc / rate_desc — by rating
  response:
    getAggregateOk: Course information successfully generated.
    getAggregateListOk: List of courses successfully generated.
    notFound: Course with the specified identifier not found.
    badRequest: Response could not be generated due to invalid request parameters. See the error message for details.
    serviceUnavailable: Response could not be generated because one of the external systems is unavailable. See the error message for details.

