spring:
  datasource:
    # Environmental variables for logins, pw and url's
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    show_sql: false

external:
  discovery-service-url: ${DISCOVERY_SERVICE_URL}
  zipkin-endpoint: ${ZIPKIN_URL}
  loki-url: ${LOKI_URL}

