server:
  port: 9096
  shutdown: graceful
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 20s
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: dispatcher-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  kafka:
    bootstrap-servers: localhost:9097
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        enable.idempotence: true
        acks: all

kafkaprops:
  enrollment-dispatch-topic: v1.enrollments_dispatch
  enrollment-placed-topic: v1.public.enrollments_outbox
  replication-factor: 1
  partitions-count: 3
  nack-sleep-duration: 100ms

external:
  zipkin-endpoint: http://localhost:9411/api/v2/spans
  loki-url: http://localhost:3100/loki/api/v1/push

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: b3
    zipkin:
      tracing:
        endpoint: ${external.zipkin-endpoint}

  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
    enable:
      jvm: true
      http:
        server: true
      hikaricp: true
      tomcat: true
      executor: true
