spring:
  datasource: #replaced R2DBC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 16
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${FLYWAY_DB_URL}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}

external:
  discovery-service-url: ${DISCOVERY_SERVICE_URL}
  #   # Increase Timeout to connect to Course Service
  default-timeout: 5s
  zipkin-endpoint: ${ZIPKIN_URL}
  loki-url: ${LOKI_URL}