spring:
  # Environmental variables for logins, pw and url's
  r2dbc:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${FLYWAY_DB_URL}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}

external:
  discovery-service-url: ${DISCOVERY_SERVICE_URL}
  #   # Increase Timeout to connect to Course Service
  default-timeout: 5s
  zipkin-endpoint: ${ZIPKIN_URL}
  keycloak-url: ${KEYCLOAK_URL}
  jwk-set-url: ${JWK_SET_URL}

management:
  endpoints:
    web:
      exposure:
        include: refresh